name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: Checkout dependencies
      run: |
        git clone https://github.com/TheSoteriaProject/SoteriaA.git

    - name: Folder Change
      run: cd SoteriaA

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Test
      run: go run main.go
