name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Checkout Dependencies
      run: |
        git clone https://github.com/TheSoteriaProject/Soteria.git

    - name: Run Soteria - Disbaled Docker Analyzer | Makefile Analyzers
      run: |
        cd Soteria/Soteria
        go build
        ./Soteria --enableMakefile=false --enableDockerfile=false ../Files

    - name: Run Soteria - Disbaled Docker Analyzer | Makefile Analyzers | enablePrintsLogs
      run: |
        cd Soteria/Soteria
        go build
        ./Soteria --enablePrintLogs=false --enableMakefile=false --enableDockerfile=false ../Files

    - name: Run Soteria - Bad File Path
      run: |
        cd Soteria/Soteria
        go build
        ./Soteria --enablePrintLogs=false --enableMakefile=false --enableDockerfile=false ../BaconRepo

    - name: Run Soteria - Help
      run: |
        cd Soteria/Soteria
        go build
        ./Soteria --help

    - name: Run Soteria Action
      run: |
        cd Soteria/Soteria
        go build
        ./Soteria ../Files
